### PR TITLE
changes some .format to f string

### PR DESCRIPTION
**Pull request by Cryptex-github**
nono don't merge it yet is far away from done

### CODE REVIEW

**Comment by ConnorTippets** [comment]
am i safe to merge this now

**Comment by ConnorTippets** [comment]
...i.. just want to know...

**Comment by Cryptex-github** [comment]
nono not safe

**Comment by ConnorTippets** [comment]
is it ever gonna be safe

**Comment by ConnorTippets** [comment]
hello?

**Comment by Cryptex-github** [comment]
maybe

**Comment by ConnorTippets** [comment]
oh my god

**Comment by Cryptex-github** [comment]
m e a n

**Comment by ConnorTippets** [comment]
who can blame me after what you've said about my code and me

**Pull request merged**
